// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repo

import (
	"time"
)

type Url struct {
	ID         int64
	OrignalUrl string
	ShortCode  string
	IsCustom   bool
	CreatedAt  time.Time
	ExpiredAt  time.Time
}
