// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repo

import (
	"context"
)

type Querier interface {
	CreateURL(ctx context.Context, arg CreateURLParams) (Url, error)
	DeleteExpiredURLs(ctx context.Context) error
	GetURLByShortCode(ctx context.Context, shortCode string) (Url, error)
	IsShortCodeAvaliable(ctx context.Context, shortCode string) (bool, error)
}

var _ Querier = (*Queries)(nil)
